### ISSUE TITLE
Reactions - Clickable Likes Link & Layout Suggestion

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#155] opened 2018-03-29 19:00 UTC
Add-on Name: Reactions

Add-on Version: Latest

XenForo Version: Latest

Suggestion:
Please replace "Likes" with "Reactions", and make the link clickable to give results (as seen in screenshot) like all reactions that member has received (just like clicking points displays what trophies that person received).

This was closed because there are some clickable links now in the profile sidebar widget, but this isn't complete.

![reactions_suggestion](https://user-images.githubusercontent.com/35111972/38107978-723c7936-3361-11e8-9825-77e98586d368.png)

This way you can also create a cool box as seen in this suggestion (you can use this idea if you want - no credit required):
https://github.com/Audentio/xf2addon-issues/issues/137

I think that sort of thing could be really attractive?

**Comment by JakeBooher** [comment] 2018-04-11 15:32
Marking this as duplicate of #156 only because they use the same Macro to handle this :)

**Closed by JakeBooher** 2018-04-11 15:32 UTC
Labels: duplicate
