### ISSUE TITLE
UI.X Pro Report Resolve Error

### ISSUE THREAD

**Issue by victoriad1** [Audentio/xf2addon-issues#1123] opened 2018-11-05 22:03 UTC
On a demo board, when I click "resolve" in the UI.X Pro Report, I get an error saying "Oops! We ran into some problems. The requested page could not be found." I didn't check all of them but it does it for a lot of them. None of the ones I tried did anything else.

**Comment by LukasWieditz** [comment] 2019-01-18 11:15
Duplicate of #1086

**Closed by LukasWieditz** 2019-01-18 11:15 UTC
Labels: Priority❕, bug
