### ISSUE TITLE
[TH] Install & Upgrade - [E_WARNING] count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#818] opened 2018-09-26 16:26 UTC
Server error log after adding profiles XenForo Customer Area.

````
ErrorException: [E_WARNING] count(): Parameter must be an array or an object that implements Countable src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Selector.php:171 

Generated by: Nirjonadda Sep 26, 2018 at 5:23 PM 

Stack trace

#0 [internal function]: XF::handlePhpError(2, '[E_WARNING] cou...', '/home/nminfo/pu...', 171, Array)
#1 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Selector.php(171): count('meta')
#2 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Selector.php(69): PHPHtmlParser\Selector->seek(Array, Array, Array)
#3 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom/AbstractNode.php(367): PHPHtmlParser\Selector->find(Object(PHPHtmlParser\Dom\HtmlNode))
#4 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php(621): PHPHtmlParser\Dom\AbstractNode->find(Object(PHPHtmlParser\Selector), 0)
#5 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php(190): PHPHtmlParser\Dom->detectCharset()
#6 src/addons/ThemeHouse/InstallAndUpgrade/vendor/paquettg/php-html-parser/src/PHPHtmlParser/Dom.php(132): PHPHtmlParser\Dom->loadStr('<!DOCTYPE html>...', Array)
#7 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/XenForo.php(183): PHPHtmlParser\Dom->load('<!DOCTYPE html>...')
#8 src/addons/ThemeHouse/InstallAndUpgrade/InstallAndUpgrade/XenForo.php(120): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\XenForo->getLicenseId()
#9 src/addons/ThemeHouse/InstallAndUpgrade/Entity/InstallUpgradeProfile.php(35): ThemeHouse\InstallAndUpgrade\InstallAndUpgrade\XenForo->getProductsFromProvider(Object(ThemeHouse\InstallAndUpgrade\Entity\InstallUpgradeProfile))
#10 src/addons/ThemeHouse/InstallAndUpgrade/Job/FetchProducts.php(19): ThemeHouse\InstallAndUpgrade\Entity\InstallUpgradeProfile->getProductsFromProvider()
#11 src/XF/Job/Manager.php(241): ThemeHouse\InstallAndUpgrade\Job\FetchProducts->run(7.9999980926514)
#12 src/XF/Job/Manager.php(187): XF\Job\Manager->runJobInternal(Array, 7.9999980926514)
#13 src/XF/Job/Manager.php(103): XF\Job\Manager->runJobEntry(Array, 7.9999980926514)
#14 src/XF/Admin/Controller/Tools.php(120): XF\Job\Manager->runByIds(Array, 8)
#15 src/XF/Mvc/Dispatcher.php(249): XF\Admin\Controller\Tools->actionRunJob(Object(XF\Mvc\ParameterBag))
#16 src/XF/Mvc/Dispatcher.php(88): XF\Mvc\Dispatcher->dispatchClass('XF:Tools', 'RunJob', 'html', Object(XF\Mvc\ParameterBag), 'tools', Object(XF\Admin\Controller\Tools), NULL)
#17 src/XF/Mvc/Dispatcher.php(41): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#18 src/XF/App.php(1931): XF\Mvc\Dispatcher->run()
#19 src/XF.php(328): XF\App->run()
#20 admin.php(13): XF::runApp('XF\\Admin\\App')
#21 {main}

Request state

array(4) {
  ["url"] => string(24) "/admin.php?tools/run-job"
  ["referrer"] => string(144) "/admin.php?tools/run-job&only_ids=109&_xfRedirect=https%3A%2F%2Fmysite.info%2Fadmin.php%3Finstall-upgrade-profiles%2F"
  ["_GET"] => array(1) {
    ["tools/run-job"] => string(0) ""
  }
  ["_POST"] => array(3) {
    ["_xfRedirect"] => string(59) "/admin.php?install-upgrade-profiles/"
    ["_xfToken"] => string(8) "********"
    ["only_ids"] => string(3) "109"
  }
}
````

**Comment by LukasWieditz** [comment] 2018-09-27 10:47
Duplicate of #820

**Closed by LukasWieditz** 2018-09-27 10:47 UTC
