### ISSUE TITLE
[Topics] Add option disable Topics filtering

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1175] opened 2018-11-23 16:49 UTC
Please add option disable Topics filtering show in Thread list, only show in Topics list.

![screenshot00746](https://user-images.githubusercontent.com/6899856/48954015-14c5ef00-ef48-11e8-92d8-360d51b9bf08.png)

**Comment by jonw316** [comment] 2019-01-18 11:31
Duplicate of #1276.

**Closed by jonw316** 2019-01-18 11:31 UTC
Labels: enhancement
