### ISSUE TITLE
Reactions - Please add widgets to give us some top reactions statistics

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#148] opened 2018-02-27 18:33 UTC
Add-on Name: Reactions

Add-on Version: Latest

XenForo Version: Latest

Suggestion / Enhancement: I know you guys are working on allowing some deeper "top"-type statistics somewhere for the members page or elsewhere (via tabs or something), but I would also like to make sure there are widgets that can be used anywhere we wish using the widget system. For example, the below link is a page built only with widgets. We would like to be able to show various Reaction top 5's/10's in widgets, configurable perhaps for example last week, last 30 days, and all time of who has the most of a particular rating, etc.

https://www.wtf.com/popular/

People can also put this in their sidebar anywhere they use sidebars... It would be nice to have more than one option that can be added for statistics.

There are a range of add-ons that use XF-native likes to show stats (including XF's own member page showing stats -- no reactions are available there). It would be nice to be able to have Reactions available to display to really be a full replacement for native likes.

Thank you!

**Comment by JakeBooher** [comment] 2018-03-28 20:03
I think this may be a duplicate of #130

**Closed by JakeBooher** 2018-03-28 20:03 UTC
Labels: duplicate
