### ISSUE TITLE
Bug when updating to 

### ISSUE THREAD

**Issue by Edrondol** [Audentio/xf2addon-issues#2222] opened 2020-09-14 17:58 UTC
Add-on Name: Reactions Plus

Add-on Version: 1.0.3 Patch Level 4

XenForo Version: 2.1.10 Patch 2

Summary of issue:

Upgrading to new version of Reactions Plus brought down the whole site and only displays the error:

An exception occurred: [ErrorException] [E_WARNING] Declaration of ThemeHouse\ReactPlus\XF\Template\Templater::fnReaction($templater, &$escape, array $config) should be compatible with ThemeHouse\Reactions\XF\Template\Templater::fnReaction($templater, &$escape, $reaction, $class = '', $hideDimensions = false) in src/addons/ThemeHouse/ReactPlus/XF/Template/Templater.php on line 0

XF::handlePhpError() in src/vendor/composer/ClassLoader.php at line 444
include() in src/vendor/composer/ClassLoader.php at line 444
Composer\Autoload\includeFile() in src/vendor/composer/ClassLoader.php at line 322
Composer\Autoload\ClassLoader->loadClass()
spl_autoload_call()
class_exists() in src/XF/Extension.php at line 172
XF\Extension->extendClass() in src/XF/App.php at line 2674
XF\App->extendClass() in src/XF/App.php at line 1678
XF\App->setupTemplaterObject() in src/XF/App.php at line 1309
XF\App->XF\{closure}() in src/XF/Container.php at line 28
XF\Container->offsetGet() in src/XF/App.php at line 2974
XF\App->templater() in src/XF/Pub/App.php at line 424
XF\Pub\App->preRender() in src/XF/Mvc/Dispatcher.php at line 395
XF\Mvc\Dispatcher->render() in src/XF/Mvc/Dispatcher.php at line 58
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2190
XF\App->run() in src/XF.php at line 391
XF::runApp() in index.php at line 20

Detailed steps to reproduce the issue:

Upgraded to XF version 2.1.10 Patch 2 and then tried to upgrade the Reactions addon.

**Comment by LukasWieditz** [comment] 2020-09-21 15:33
Duplicate of #2204

**Closed by LukasWieditz** 2020-09-21 15:33 UTC
