### ISSUE TITLE
Reactions - Latest activity entries showing after uninstall

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2addon-issues#1453] opened 2019-02-02 00:57 UTC
As per title; after uninstalling Reactions old latest activity entries haven't been deleted. Resulting in following errors:
```ErrorException: Template error: Template public:news_feed_item_post_react is unknown src/XF/Template/Templater.php:611

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/fellowsfi...', 611, Array)
#1 src/XF/Template/Templater.php(611): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(562): XF\Template\Templater->getTemplateData('public', 'news_feed_item_...')
#3 src/XF/Template/Templater.php(1293): XF\Template\Templater->getTemplateCode('public', 'news_feed_item_...')
#4 src/XF/NewsFeed/AbstractHandler.php(102): XF\Template\Templater->renderTemplate('news_feed_item_...', Array)
#5 src/XF/Entity/NewsFeed.php(79): XF\NewsFeed\AbstractHandler->render(Object(XF\Entity\NewsFeed))
#6 [internal function]: XF\Entity\NewsFeed->render()
#7 src/XF/Template/Templater.php(978): call_user_func_array(Array, Array)
#8 internal_data/code_cache/templates/l1/s13/public/news_feed_macros.php(34): XF\Template\Templater->method(Object(XF\Entity\NewsFeed), 'render', Array)
#9 src/XF/Template/Templater.php(694): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#10 internal_data/code_cache/templates/l1/s13/public/news_feed_macros.php(12): XF\Template\Templater->callMacro('news_feed_macro...', 'feed_item', Array, Array)
#11 src/XF/Template/Templater.php(694): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#12 internal_data/code_cache/templates/l1/s13/public/member_latest_activity.php(32): XF\Template\Templater->callMacro('news_feed_macro...', 'feed_row', Array, Array)
#13 src/XF/Template/Templater.php(1294): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#14 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('member_latest_a...', Array)
#15 src/XF/Mvc/Renderer/Html.php(48): XF\Template\Template->render()
#16 src/XF/Mvc/Dispatcher.php(418): XF\Mvc\Renderer\Html->renderView('XF:Member\\Lates...', 'public:member_l...', Array)
#17 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#18 src/XF/Mvc/Dispatcher.php(360): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Html), Object(XF\Mvc\Reply\View))
#19 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#20 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#21 src/XF.php(390): XF\App->run()
#22 index.php(20): XF::runApp('XF\\Pub\\App')
#23 {main}
```

And this:
![image](https://user-images.githubusercontent.com/34864926/52157241-84153900-2685-11e9-9e93-f3c367bcfca4.png)

**Comment by jonw316** [comment] 2019-02-11 15:43
Duplicate of #1433.

**Closed by jonw316** 2019-02-11 15:43 UTC
