### ISSUE TITLE
[TH] Topics - Template error: Template public:th_topicCache_topics.less is unknown

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1101] opened 2018-11-01 10:33 UTC
Getting Server error log after updated to 1.0.0 Patch Level 1

````
ErrorException: Template error: Template public:th_topicCache_topics.less is unknown src/XF/Template/Templater.php:584 

Generated by: Unknown account Nov 1, 2018 at 4:25 PM 

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/nadda/pub...', 584, Array)
#1 src/XF/Template/Templater.php(584): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(539): XF\Template\Templater->getTemplateData('public', 'th_topicCache_t...')
#3 src/XF/Template/Templater.php(1249): XF\Template\Templater->getTemplateCode('public', 'th_topicCache_t...')
#4 src/addons/AddonsLab/LinkChecker/XF/Template/Templater.php(89): XF\Template\Templater->renderTemplate('th_topicCache_t...', Array, true)
#5 src/XF/Template/Templater.php(1324): AddonsLab\LinkChecker\XF\Template\Templater->renderTemplate('public:th_topic...', Array)
#6 internal_data/code_cache/templates/l1/s10/public/thtopics.less.php(397): XF\Template\Templater->includeTemplate('public:th_topic...', Array)
#7 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#8 src/addons/AddonsLab/LinkChecker/XF/Template/Templater.php(89): XF\Template\Templater->renderTemplate('thtopics.less', Array, false)
#9 src/XF/CssRenderer.php(297): AddonsLab\LinkChecker\XF\Template\Templater->renderTemplate('public:thtopics...', Array, false)
#10 src/XF/CssRenderer.php(235): XF\CssRenderer->renderTemplate('public:thtopics...', NULL)
#11 src/XF/CssRenderer.php(101): XF\CssRenderer->renderTemplates(Array, Array, Array)
#12 src/XF/CssWriter.php(53): XF\CssRenderer->render(Array)
#13 src/addons/SV/RedisCache/XF/CssWriter.php(23): XF\CssWriter->run(Array, 10, 1, '3627ad0a6dfa62a...')
#14 css.php(30): SV\RedisCache\XF\CssWriter->run(Array, 10, 1, '3627ad0a6dfa62a...')
#15 {main}

Request state

array(4) {
  ["url"] => string(639) "/css.php?css=public%3AGoogleSearch.less%2Cpublic%3Aandy_similarthreads.less%2Cpublic%3Aeditor.less%2Cpublic%3Akl_em_editor_templates.less%2Cpublic%3Akl_em_froala_fullscreen.less%2Cpublic%3Akl_em_froala_image.less%2Cpublic%3Akl_em_froala_table.less%2Cpublic%3Aprefix_menu.less%2Cpublic%3Aselect2.less%2Cpublic%3Asv_livecontent.less%2Cpublic%3Ath_covers.less%2Cpublic%3Ath_giphy.less%2Cpublic%3Ath_nodeStyling_nodes.10.less%2Cpublic%3Ath_slick_giphy.css%2Cpublic%3Athtopics.less%2Cpublic%3Athtopics_topic_cache.less%2Cpublic%3Athtopics_topic_chooser.less%2Cpublic%3Aextra.less&s=10&l=1&d=1541067437&k=3627ad0a6dfa62a6d60efc23313c074fb919a585"
  ["referrer"] => string(57) "/forums/desi-picture.83/post-thread"
  ["_GET"] => array(5) {
    ["css"] => string(491) "public:GoogleSearch.less,public:andy_similarthreads.less,public:editor.less,public:kl_em_editor_templates.less,public:kl_em_froala_fullscreen.less,public:kl_em_froala_image.less,public:kl_em_froala_table.less,public:prefix_menu.less,public:select2.less,public:sv_livecontent.less,public:th_covers.less,public:th_giphy.less,public:th_nodeStyling_nodes.10.less,public:th_slick_giphy.css,public:thtopics.less,public:thtopics_topic_cache.less,public:thtopics_topic_chooser.less,public:extra.less"
    ["s"] => string(2) "10"
    ["l"] => string(1) "1"
    ["d"] => string(10) "1541067437"
    ["k"] => string(40) "3627ad0a6dfa62a6d60efc23313c074fb919a585"
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by JakeBooher** [comment] 2018-11-08 17:45
This is happening on a new install of 1.0.0 Patch Level 2.

**Comment by jonw316** [comment] 2018-11-08 17:46
Take a look at my comment above.

**Comment by JakeBooher** [comment] 2018-11-08 17:49
I saw your comment above. There are no unmerged templates, it's a **new** install of 1.0.0 Patch Level 2.

**Comment by jonw316** [comment] 2018-11-08 17:52
The issue is with UI.X. Closing again. Please don't re-open.

**Closed by jonw316** 2018-11-08 17:52 UTC
Labels: Bug, Confirmed, Priority
