### ISSUE TITLE
If using filter component on a page that doesn't actually have filterable content, link to page that does (the main home)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#632] opened 2018-07-18 16:35 UTC
Not sure if this is tricky or not. Point being that if I want topic filter widget global, as a means to quickly jump to that main filtered list of content, I should be able to do that. Instead it just doesn't do anything. 

This is currently an issue as NeoGAF needs this.

**Comment by LukasWieditz** [comment] 2018-07-19 13:41
Duplicate of #634 I think

**Closed by LukasWieditz** 2018-07-19 13:41 UTC
Labels: Bug
