### ISSUE TITLE
Icon for reply/comment link

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#420] opened 2018-05-24 12:51 UTC
Post comments button is currently missing an icon in UI.X. Class is `actionBar-action actionBar-action--comment`.

**Comment by Ian-Hitt** [comment] 2018-05-25 17:51
@LukasWieditz this is a duplicate of a fixed issue.

**Closed by Ian-Hitt** 2018-05-25 17:51 UTC
Labels: enhancement

**Comment by LukasWieditz** [comment] 2018-05-25 17:54
For reference: Audentio/xf2theme-issues#639
