### ISSUE TITLE
[TH] Reactions > New Style Property: "Display Reactions bar location"

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#106] opened 2018-01-07 15:34 UTC
Please add Support moving Reactions bar under or above content controls.

**Comment by JakeBooher** [comment] 2018-01-07 19:32
Duplicate of #85

**Closed by JakeBooher** 2018-01-07 19:32 UTC
Labels: duplicate

**Comment by Nirjonadda** [comment] 2018-01-08 17:08
Maked as Duplicate but implemented, very strange things. I think we need go back using Xon Version because xon Version happened lot of improvement.

https://image.prntscr.com/image/CsjyQ-dcQkeWlAFemMLfbQ.png
