### ISSUE TITLE
Nodes - Unexpected contents

### ISSUE THREAD

**Issue by teamracing** [Audentio/xf2addon-issues#2373] opened 2020-11-21 04:20 UTC
Add-on Name: Nodes

Add-on Version: 1.1.0

XenForo Version: 2.2.1

Summary of issue:

**js/themehouse/global/20180112.min.js Unexpected contents**

**Comment by LukasWieditz** [comment] 2020-11-23 08:58
Duplicate of #2246

**Closed by LukasWieditz** 2020-11-23 08:58 UTC
