### ISSUE TITLE
Topics - On layout manager, show a label with meaning of the line

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#992] opened 2018-10-23 20:23 UTC
![image](https://user-images.githubusercontent.com/1217271/47388353-8e638680-d6d7-11e8-80e1-b465be9460d6.png)

**Comment by jonw316** [comment] 2018-10-24 12:41
Duplicate of #929

**Closed** 2018-10-24 12:41 UTC
Labels: Duplicate, Enhancement
