### ISSUE TITLE
Improvement of space for posting a thread with lots of topics

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#750] opened 2018-09-18 15:33 UTC
![image](https://user-images.githubusercontent.com/1217271/45698673-2812a380-bb2e-11e8-8c0e-49a0a2202899.png)

Ultimately, I think we need to remove the huge grid of items and do a modal but we should be specific.

- [x] Ask for primary topic
- [x] Bug: There is no way to change the primary topic (which I get is kinda due to the fact that create thread needs a forum but posting here anyway)
- [ ] Secondary topics should be asked for, but I was thinking in a modal (Ian suggests a dropdown animation)
- [ ] If secondary ones are selected, they should display at the top of crreate thread under the primary one as labels with an option to add more. An 'X' next to each one like filterbar has is nice as well

**Comment by mikecreuzer** [comment] 2018-09-18 15:34
@Ian-Hitt let me know if you need a visual. Ultimately we need to let people know what they are selecting, but if they want to add more I think the modal experience is best

**Comment by Ian-Hitt** [comment] 2018-09-18 16:00
@mikecreuzer this is a duplicate of https://github.com/Audentio/xf2addon-issues/issues/695

**Comment by mikecreuzer** [comment] 2018-09-18 16:41
As my issue is more detailed and specific, going to reverse that closing :P

**Comment by mikecreuzer** [comment] 2018-09-19 14:26
Well this depends too @jonw316 because it depends on how many topics we have. If a site has 10, its not a bad idea to just list them like we are. But if they have 100, its going to get difficult. Maybe a setting to toggle them into a modal?

**Comment by jonw316** [comment] 2018-09-19 14:30
If "Family" is the only possible topic for that forum, then there is no point having an option to select it.

I'll add an option to limit the number of secondary topics that show and add an "All Topics" link like on the widget that opens up a modal.

**Comment by mikecreuzer** [comment] 2018-09-19 14:34
That works.

Regarding the only possible topic. That is a technical limitation, but not actually something that the UX needs to care about. You could simply let people rechoose their primary topic on this view, and then it would thus change the node (as that topic will be associated with a new node)

Could require modifying the <form action> or something Im not sure. If its not easy we can skip. Its just people who dont want that primary topic would need to close out and go find a new primary. Same goes for edit, which I dont know if we want people to be able to do, but they wont be able to change their primary topic.

**Comment by jonw316** [comment] 2018-09-19 14:36
At the moment it only offers the list of possible primary topics for that forum anyway -- it doesn't list all of them.

**Comment by mikecreuzer** [comment] 2018-09-19 14:37
I can live with not having this ability. To me its like retriggering the global Create Thread modal again, as that asks for primary there, then secondary. Only difference is that it would edit, and not refresh or take you away from the page. But that is fine.

**Comment by jonw316** [comment] 2018-09-19 14:41
The edit currently allows people to change to any primary topic and moves the thread to a different forum if required. I think this is probably all the right way round.

**Closed** 2018-09-20 14:09 UTC
Labels: Priority
