### ISSUE TITLE
Reactions - Deletion of member results in odd error?

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2addon-issues#842] opened 2018-10-01 16:09 UTC
Add-on Name: Reactions

Add-on Version: Latest

XenForo Version: Latest

Operating System (and Version): Windows 10 - 64 bit (stable)

Browser Name (and Version): Chrome 69 (stable)

Summary of issue: When doing a deletion of a member (members with NO prior content even), I received this error message?

LogicException: Entity XFMG:MediaComment (class: XFMG\Entity\MediaComment) could not be found in src/XF/Mvc/Entity/Manager.php at line 51
XF\Mvc\Entity\Manager->getEntityClassName() in src/XF/Mvc/Entity/Manager.php at line 660
XF\Mvc\Entity\Manager->instantiateEntity() in src/XF/Mvc/Entity/Manager.php at line 106
XF\Mvc\Entity\Manager->create() in src/addons/ThemeHouse/Reactions/Service/User/Deleter.php at line 90
ThemeHouse\Reactions\Service\User\Deleter->pruneReactUsersCacheForEntity() in src/addons/ThemeHouse/Reactions/Service/User/Deleter.php at line 275
ThemeHouse\Reactions\Service\User\Deleter->stepPruneMediaCommentReactUserCacheData() in src/XF/MultiPartRunnerTrait.php at line 48
ThemeHouse\Reactions\Service\User\Deleter->runLoop() in src/addons/ThemeHouse/Reactions/Service/User/Deleter.php at line 69
ThemeHouse\Reactions\Service\User\Deleter->delete() in src/addons/ThemeHouse/Reactions/Job/DeleteUserReactions.php at line 31
ThemeHouse\Reactions\Job\DeleteUserReactions->run() in src/XF/Job/Manager.php at line 241
XF\Job\Manager->runJobInternal() in src/XF/Job/Manager.php at line 187
XF\Job\Manager->runJobEntry() in src/XF/Job/Manager.php at line 103
XF\Job\Manager->runByIds() in src/XF/Admin/Controller/Tools.php at line 120
XF\Admin\Controller\Tools->actionRunJob() in src/XF/Mvc/Dispatcher.php at line 249
XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 88
XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 41
XF\Mvc\Dispatcher->run() in src/XF/App.php at line 1931
XF\App->run() in src/XF.php at line 329
XF::runApp() in admin.php at line 13

**Comment by daltonp** [comment] 2018-10-01 16:28
I was able to replicate this on one of our demo's as well. I've gone ahead and marked it as a bug so that it is fixed in the next few updates.

**Comment by jonw316** [comment] 2018-10-01 17:03
This is a duplicate of #833.

**Closed by jonw316** 2018-10-01 17:03 UTC
Labels: Bug
