### ISSUE TITLE
[TH] Install & Upgrade - Zip install are not show in Installed products 

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#973] opened 2018-10-19 22:41 UTC
Zip install are not show in Installed products for other add-on, out site in Xenforo RM download.

See this installation: https://github.com/Audentio/xf2addon-issues/issues/972

**Comment by LukasWieditz** [comment] 2018-10-22 10:01
Unless they carry the required meta-data (which they won't, because we haven't released install & upgrade yet so developers can package that into their add-ons), that's expected behavior. Install & upgrade can hardly guess where you downloaded the zip file from.

**Comment by LukasWieditz** [comment] 2018-10-22 10:02
Unless they carry the required meta-data (which they won't, because we haven't released install & upgrade yet so developers can package that into their add-ons), that's expected behavior. Install & upgrade can hardly guess where you downloaded the zip file from.

**Closed by LukasWieditz** 2018-10-22 10:01 UTC

**Comment by LukasWieditz** [comment] 2018-10-22 10:28
That is expected behavior. Install & Upgrade can hardly guess where you downloaded the zip file from. Unless the developer of the respective add-on adds the required metadata for Install & Upgrade (which they can't until the add-on has been released), that won't be possible.
