### ISSUE TITLE
[Donate] Campaign goal amount progress bar isn't rounded on both sides

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#1130] opened 2018-11-07 19:17 UTC
![screen shot 2018-11-07 at 1 16 56 pm](https://user-images.githubusercontent.com/32306910/48154971-8555e600-e28f-11e8-9157-40e9b8a7cf61.png)

**Comment by evertiro** [comment] 2019-01-04 17:17
It's missing a tiny bit of CSS. Add the following to your `extra.less`:

```css
.donate-progressBarContainer {
    overflow: hidden;
}
```

**Comment by JakeBooher** [comment] 2019-04-26 19:50
Duplicate of #1302

**Closed** 2019-04-29 15:25 UTC
Labels: duplicate
