### ISSUE TITLE
Add functionality to allow administrators to remove the node background image on the node header

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#561] opened 2018-06-21 18:45 UTC
![screen shot 2018-06-21 at 1 43 35 pm](https://user-images.githubusercontent.com/32306910/41738944-35da028a-7559-11e8-98e7-376fc9cca4a8.png)

**Comment by LukasWieditz** [comment] 2018-06-22 14:37
Duplicate of #470

**Closed by LukasWieditz** 2018-06-22 14:37 UTC
Labels: Enhancement
