### ISSUE TITLE
Spotify Button Improvements

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#503] opened 2018-06-08 15:31 UTC
Login Using Button
![loginusingdefault](https://user-images.githubusercontent.com/32306910/41166757-b69716b8-6b06-11e8-93f0-00b74f362e6d.png)
![loginusingui x](https://user-images.githubusercontent.com/32306910/41166758-b6c7a94a-6b06-11e8-9c61-8e82d44a2849.png)

Profile Page Listening Button
![profilepagelisteningdefault](https://user-images.githubusercontent.com/32306910/41166784-c4f81a40-6b06-11e8-86dc-96dff47db0ef.png)
![profilepagelisteningui x](https://user-images.githubusercontent.com/32306910/41166786-c512e258-6b06-11e8-84f1-a822ec72c3c9.png)

Profile Pop-out Button
![profilepopoutdefault](https://user-images.githubusercontent.com/32306910/41166830-d85bc0c8-6b06-11e8-9e5d-e8f3721d9561.png)
![profilepopoutui x](https://user-images.githubusercontent.com/32306910/41166832-d8787d62-6b06-11e8-86cb-30fcb1e13d71.png)

Associate Spotify
![associatespotifydefault](https://user-images.githubusercontent.com/32306910/41167101-946e1c98-6b07-11e8-977c-43e38e6f7f9e.png)
![associatespotifyui x](https://user-images.githubusercontent.com/32306910/41167102-948dca70-6b07-11e8-88f2-1e98f6c5b9f4.png)

Are they supposed to have the same button style across every style? Include ours? This happens when using the version of 1.0.0.

**Comment by LukasWieditz** [comment] 2018-06-08 16:39
Duplicate of #172

**Closed by LukasWieditz** 2018-06-08 16:39 UTC
Labels: enhancement, question
