### ISSUE TITLE
Topic Filter

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1048] opened 2018-10-26 09:21 UTC
Can you get main topic filter to read sub nodes as well. As seen in screenshot, "JoyFreak" filter only filters Introductions and not Announcements in New Posts/Latest Threads/Trending/All threads. Due to the Announcements threads being in a sub node. It would be cause complications as I needed separate permissions for Announcements. If you guys add permission for Topics then it would be handy. Allowing certain usergroups to use certain topics. The only reason for a sub node Announcements is because of this. But of course, having a separate node for Announcements is better. So allowing the New Posts/Latest Threads/Trending/All threads to display the threads/posts from sub nodes would be a better solution. You could implement both of them anyway for better user flexibility and friendliness. Obviously, if possible.

![this](https://user-images.githubusercontent.com/43339306/47557553-e1705000-d908-11e8-9ae4-8f67bcc0b2fe.png)

**Comment by jonw316** [comment] 2018-10-26 09:48
Duplicate of #1050

**Closed** 2018-10-26 09:48 UTC
Labels: Bug, Duplicate
