### ISSUE TITLE
[Ignore More] Declaration error

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2315] opened 2020-10-22 14:16 UTC
Reported by one of our customers in a ticket:

```
[E_WARNING] Declaration of ThemeHouse\IgnoreMore\XF\FindNew\Thread::filterResults(XF\Mvc\Entity\ArrayCollection $results) should be compatible with XF\FindNew\Thread::filterResults(XF\Mvc\Entity\AbstractCollection $results) in src/addons/ThemeHouse/IgnoreMore/XF/FindNew/Thread.php at line 18 XF::handlePhpError() in src/addons/ThemeHouse/IgnoreMore/XF/FindNew/Thread.php at line 12 include() in src/vendor/composer/ClassLoader.php at line 444 Composer\Autoload\includeFile() in src/vendor/composer/ClassLoader.php at line 322 Composer\Autoload\ClassLoader->loadClass() spl_autoload_call() class_exists() in src/XF/Extension.php at line 172 XF\Extension->extendClass() in src/XF/App.php at line 2811 XF\App->extendClass() in src/XF.php at line 902 XF::extendClass() in src/XF/Repository/FindNew.php at line 81 XF\Repository\FindNew->getFindNewHandler() in src/XF/ControllerPlugin/FindNew.php at line 87 XF\ControllerPlugin\FindNew->getFindNewHandler() in src/XF/Pub/Controller/AbstractWhatsNewFindType.php at line 20 XF\Pub\Controller\AbstractWhatsNewFindType->actionIndex() in src/XF/Mvc/Dispatcher.php at line 350 XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 257 XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 113 XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 55 XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2300 XF\App->run() in src/XF.php at line 465 XF::runApp() in index.php at line 20
```

**Comment by LukasWieditz** [comment] 2020-10-27 14:53
Duplicate of #2264

**Closed by LukasWieditz** 2020-10-27 14:53 UTC
Labels: bug
