### ISSUE TITLE
Cover::setupDefaultCover() must be an instance of XF\Mvc\Entity\Entity, null given

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2addon-issues#1503] opened 2019-02-14 13:26 UTC
TypeError: Argument 1 passed to ThemeHouse\Covers\Pub\Controller\Cover::setupDefaultCover() must be an instance of XF\Mvc\Entity\Entity, null given, called in /var/www/----/public/src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php on line 386 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php:351

==================================================

Stack trace
#0 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(386): ThemeHouse\Covers\Pub\Controller\Cover->setupDefaultCover(NULL)
#1 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(30): ThemeHouse\Covers\Pub\Controller\Cover->assertCover('user', '2')
#2 src/XF/Pub/Controller/AbstractController.php(30): ThemeHouse\Covers\Pub\Controller\Cover->preDispatchController('Position', Object(XF\Mvc\ParameterBag))
#3 src/XF/Mvc/Controller.php(123): XF\Pub\Controller\AbstractController->preDispatchType('Position', Object(XF\Mvc\ParameterBag))
#4 src/XF/Mvc/Dispatcher.php(320): XF\Mvc\Controller->preDispatch('Position', Object(XF\Mvc\ParameterBag))
#5 src/XF/Mvc/Dispatcher.php(248): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\Cove...', 'Position', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#6 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#7 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#8 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#9 src/XF.php(390): XF\App->run()
#10 index.php(20): XF::runApp('XF\Pub\App')
#11 {main}

==================

Request state
array(4) {
["url"] => string(23) "/covers/user/2/position"
["referrer"] => bool(false)
["_GET"] => array(0) {
}
["_POST"] => array(0) {
}
}

**Comment by jonw316** [comment] 2019-02-14 13:34
Duplicate of #1200. Don't you just need to release the fix you made?

**Closed** 2019-03-04 12:03 UTC
Labels: bug, duplicate
