### ISSUE TITLE
[Donate] ErrorException: Template error: Template public:th_donate_campaign_new_comment is unknown

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#2215] opened 2020-08-25 11:14 UTC
```
ErrorException: Template error: Template public:th_donate_campaign_new_comment is unknown src/XF/Template/Templater.php:618 

Generated by: bj nath Aug 25, 2020 at 3:37 PM 

Stack trace

#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/nadda/pub...', 618, Array)
#1 src/XF/Template/Templater.php(618): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(566): XF\Template\Templater->getTemplateData('public', 'th_donate_campa...')
#3 src/XF/Template/Templater.php(1314): XF\Template\Templater->getTemplateCode('public', 'th_donate_campa...')
#4 src/addons/AddonsLab/LinkChecker/XF/Template/Templater.php(89): XF\Template\Templater->renderTemplate('th_donate_campa...', Array, true)
#5 src/XF/Template/Template.php(24): AddonsLab\LinkChecker\XF\Template\Templater->renderTemplate('public:th_donat...', Array)
#6 src/XF/Mvc/Renderer/Json.php(84): XF\Template\Template->render()
#7 src/XF/Mvc/Renderer/Json.php(68): XF\Mvc\Renderer\Json->renderHtmlFallback('ThemeHouse\\Dona...', 'public:th_donat...', Array)
#8 src/XF/Mvc/Dispatcher.php(458): XF\Mvc\Renderer\Json->renderView('ThemeHouse\\Dona...', 'public:th_donat...', Array)
#9 src/XF/Mvc/Dispatcher.php(440): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#10 src/XF/Mvc/Dispatcher.php(400): XF\Mvc\Dispatcher->renderReply(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#11 src/XF/Mvc/Dispatcher.php(58): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#12 src/XF/App.php(2190): XF\Mvc\Dispatcher->run()
#13 src/XF.php(391): XF\App->run()
#14 index.php(20): XF::runApp('XF\\Pub\\App')
#15 {main}

Request state

array(4) {
  ["url"] => string(52) "/donate/donate-to-nirjonmela.1/campaign/comments/add"
  ["referrer"] => string(70) "/donate/donate-to-nirjonmela.1/campaign/comments"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(9) {
    ["message_html"] => string(74) "<p>বিকাশ নাম্বার দিলে ভাল হয়</p>"
    ["last_date"] => string(10) "1586600935"
    ["last_known_date"] => string(10) "1586600935"
    ["style"] => string(0) ""
    ["context"] => string(4) "user"
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(48) "/donate/donate-to-nirjonmela.1/campaign/comments"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
```

**Comment by LukasWieditz** [comment] 2020-09-03 10:11
Duplicate of #2157

**Closed by LukasWieditz** 2020-09-03 10:11 UTC
Labels: bug
