### ISSUE TITLE
[TH] Topics - Disable Enable thread topics system are not remove Widgets

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1194] opened 2018-11-27 15:45 UTC
Disable Enable thread topics system are not remove Widgets from New threads and New posts.

![screenshot00757](https://user-images.githubusercontent.com/6899856/49092877-43530b00-f263-11e8-8af3-0c13ac21b5fb.png)

**Comment by jonw316** [comment] 2018-11-27 15:49
That is node topics widget and not a thread topics widget, so this is correct that it is not removed.

**Comment by Nirjonadda** [comment] 2018-11-27 16:02
What add-on adding this? This added by [TH] Topics add-on. So how to disable this? Disabling add-on will remove this widget.

![screenshot00758](https://user-images.githubusercontent.com/6899856/49094205-01779400-f266-11e8-9e9a-96415bf3e289.png)

**Comment by jonw316** [comment] 2018-11-27 16:04
There are 2 systems: the thread topics system and the node topics system. The thread topics system can be disabled with that option. The node topics system cannot be disabled except by disabling the add-on.

**Comment by mikecreuzer** [comment] 2018-11-27 16:39
@Nirjonadda yeah there are 2 systems here, one is node topics the other is thread topics.

@jonw316 to help make it more clear, should we simply have a radio button instead of a global enable of Topics? That way its clear that you are wanting "nodes" or "threads" topic experiences. Its a small thing to just make sure people know whats going on

**Comment by jonw316** [comment] 2018-11-27 16:40
What if you want both?

**Comment by jonw316** [comment] 2018-11-27 16:49
Duplicate of #1196.

**Closed by jonw316** 2018-11-27 16:49 UTC
Labels: Wont Fix
