### ISSUE TITLE
[TH] Nodes - node title are not visible

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#469] opened 2018-06-01 13:45 UTC
node title are not visible, need some improvement.

![screenshot00141](https://user-images.githubusercontent.com/6899856/40843914-d4bdd9c8-65b2-11e8-9bd6-1e90f5844348.png)

**Comment by LukasWieditz** [comment] 2018-06-01 17:06
Duplicate of #465

**Closed by LukasWieditz** 2018-06-01 17:06 UTC
