### ISSUE TITLE
Hover on topics in page title

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2addon-issues#494] opened 2018-06-07 18:18 UTC
![hover](https://user-images.githubusercontent.com/1217271/41118331-3b80eb90-6a55-11e8-9dc2-276b6ba322a9.gif)

**Comment by LukasWieditz** [comment] 2018-06-07 18:21
Duplicate of #491

**Closed by LukasWieditz** 2018-06-07 18:21 UTC
