### ISSUE TITLE
[Donate] No template included for th_donate_campaign_new_comment

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2addon-issues#2175] opened 2020-06-10 15:03 UTC
This was reported by [Robert9](https://xenforo.com/community/threads/th-donate-paid.145264/post-1431638) on xenforo.com:

_In donate.php you have_

```
            $view = $this->view('ThemeHouse\Donate:Donation\NewComments', 'th_donate_campaign_new_comment',
                $viewParams);
```
but there is no template with this name: th_donate_campaign_new_comment

**Comment by LukasWieditz** [comment] 2020-06-15 15:00
Duplicate of #2157

**Closed by LukasWieditz** 2020-06-15 15:00 UTC
Labels: bug, duplicate
