### ISSUE TITLE
[TH] Reactions - Always Show Secondary Trigger

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#392] opened 2018-05-23 15:06 UTC
If enabled Always Show Secondary Trigger then Default reaction should not be open popup because its will be direct take action. only Always Show Secondary Trigger will be show popup when enabled.

**Comment by mikecreuzer** [comment] 2018-05-23 16:22
Its on our milestone to fix this, but I think this is a duplicate of https://github.com/Audentio/xf2addon-issues/issues/267 (reopen if not)

**Closed by mikecreuzer** 2018-05-23 16:22 UTC
