### ISSUE TITLE
[TH] Connected Account Providers Error

### ISSUE THREAD

**Issue by hasannakyuz** [Audentio/xf2addon-issues#2069] opened 2020-01-18 12:11 UTC
Add-on Name:  [TH] Connected Account Providers

Add-on Version: 1.0.0

XenForo Version: 2.1.6

Operating System (and Version): 2.1.6

Browser Name (and Version): 

Summary of issue: error when uninstalling plugin

Detailed steps to reproduce the issue: 

Upload any screenshots related to the issue below
![Adsız](https://user-images.githubusercontent.com/58447473/72663532-d8373b80-3a04-11ea-9dc0-7a25fc58caeb.png)

**Comment by LukasWieditz** [comment] 2020-01-30 11:00
Duplicate of #2074

**Closed by LukasWieditz** 2020-01-30 11:00 UTC
