### ISSUE TITLE
Covers error log

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2addon-issues#1776] opened 2019-05-08 07:04 UTC
I have 7 error logs this morning with the following:
Server error log
Error: Call to undefined method XF\Mvc\Reply\View::canPositionImage() src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php:201
Generated by: Unknown account May 8, 2019 at 6:34 AM
Stack trace
#0 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\Covers\Pub\Controller\Cover->actionPosition(Object(XF\Mvc\ParameterBag))
#1 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Position', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#2 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#3 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#4 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#5 src/XF.php(390): XF\App->run()
#6 index.php(20): XF::runApp('XF\\Pub\\App')
#7 {main}
Request state
array(4) {
  ["url"] => string(24) "/covers/user/80/position"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by joyfreak** [comment] 2019-05-10 10:32
Server error log
LogicException: Content type resource must define an 'entity' value src/XF/App.php:2561
Generated by: Unknown account May 10, 2019 at 11:16 AM
Stack trace
#0 src/XF/App.php(2538): XF\App->getContentTypeEntity('resource')
#1 src/addons/ThemeHouse/Covers/Cover/AbstractHandler.php(25): XF\App->findByContentType('resource', '2', Array)
#2 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(398): ThemeHouse\Covers\Cover\AbstractHandler->getContent('2')
#3 src/addons/ThemeHouse/Covers/Pub/Controller/Cover.php(27): ThemeHouse\Covers\Pub\Controller\Cover->assertCover('resource', '2')
#4 src/XF/Pub/Controller/AbstractController.php(30): ThemeHouse\Covers\Pub\Controller\Cover->preDispatchController('Position', Object(XF\Mvc\ParameterBag))
#5 src/XF/Mvc/Controller.php(123): XF\Pub\Controller\AbstractController->preDispatchType('Position', Object(XF\Mvc\ParameterBag))
#6 src/XF/Mvc/Dispatcher.php(320): XF\Mvc\Controller->preDispatch('Position', Object(XF\Mvc\ParameterBag))
#7 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('ThemeHouse\\Cove...', 'Position', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#8 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\Covers\Pub\Controller\Cover), NULL)
#9 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#10 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#11 src/XF.php(390): XF\App->run()
#12 index.php(20): XF::runApp('XF\\Pub\\App')
#13 {main}
Request state
array(4) {
  ["url"] => string(27) "/covers/resource/2/position"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by LukasWieditz** [comment] 2019-05-14 12:44
Duplicate of #1782

**Closed by LukasWieditz** 2019-05-14 12:44 UTC
