### ISSUE TITLE
Phrases th_uix_icon and th_uix_icon_explain missing

### ISSUE THREAD

**Issue by setoy** [Audentio/xf2addon-issues#1918] opened 2019-06-30 19:31 UTC
When creating (or editing) a notice, both of these phrases are missing.
![image](https://user-images.githubusercontent.com/6497266/60401219-73a6b300-9b7e-11e9-85ab-344137e75011.png)

**Comment by LukasWieditz** [comment] 2019-07-01 09:05
Duplicate of #1902

**Closed by LukasWieditz** 2019-07-01 09:05 UTC
