### ISSUE TITLE
[TH] Covers - Modify cover image in admin CP

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#524] opened 2018-06-12 23:05 UTC
Modify cover image in admin CP are not checked by default. Its should be one Upload cover marked.

![screenshot00003](https://user-images.githubusercontent.com/6899856/41321809-ea4c9d3c-6ea5-11e8-8412-8a8d4a2494ac.png)

**Comment by LukasWieditz** [comment] 2018-06-22 11:22
Duplicate of #525 ?

**Closed by LukasWieditz** 2018-06-22 11:22 UTC
Labels: Bug
