### ISSUE TITLE
Q&A Forums - user profile -> best Answers incorrect enumeration

### ISSUE THREAD

**Issue by GH-Rake** [Audentio/xf2addon-issues#2059] opened 2019-12-30 20:25 UTC
Add-on Name:
Q&A Forums

Add-on Version:
1.1.4 Patch Level 2

XenForo Version:
v2.1.6 Patch 1

Operating System (and Version):
Win10 1903 18362.535
Server: CentMinMod NGINX

Browser Name (and Version):
Chrome, Brave & Firefox tested, all latest version

Summary of issue:
When viewing users best answers, and clicking View older results it will list all their posts in the thread where the best answer is, not just their answer.

Detailed steps to reproduce the issue:
Go to user profile
Click Best Answers (user must have many answers)
click See More
Click Next
Click View older results
if user has multiple posts in the thread, it will list all of them instead of just the answer

Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/15186628/71599339-7b88e500-2b18-11ea-8f9f-e452f1ea954a.png)

You can view this in action on this user's profile
https://guidedhacking.com/members/the_nut.93578/

**Comment by LukasWieditz** [comment] 2020-01-13 13:48
I'm not able to reproduce that. Try rebuilding your search index to see if it's a temporary issue caused by potentially outdated data.

**Comment by GH-Rake** [comment] 2020-01-13 23:45
Rebuilding the search index and disabling addons did not solve this for me.  There is one other person on the Xenforo forums who also reported this issue.

**Comment by LukasWieditz** [comment] 2020-09-03 10:05
We've unfortunately not been able to replicate this till date. As Q&A forums is going to be integrated into XenForo core starting with 2.2 and therefor our product being retired, we're closing this issue.

**Closed by LukasWieditz** 2020-09-03 10:05 UTC
Labels: bug, unable to replicate
