### ISSUE TITLE
QAForums Server error log

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#476] opened 2018-06-03 18:13 UTC
I am getting this Server error log.

````
ErrorException: Fatal Error: Access level to ThemeHouse\QAForums\XF\Pub\Controller\Thread::getNewPostsReply() must be public (as in class ThemeHouse\PostComments\XF\Pub\Controller\Thread) src/addons/ThemeHouse/QAForums/XF/Pub/Controller/Thread.php:0 

Generated by: Nirjonadda Jun 3, 2018 at 7:02 PM 

Stack trace

#0 [internal function]: XF::handleFatalError()
#1 {main}

Request state

array(4) {
  ["url"] => string(35) "/threads/node-layout-and-styling.12"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by LukasWieditz** [comment] 2018-06-05 11:18
Duplicate of #460

**Closed by LukasWieditz** 2018-06-05 11:18 UTC
