### ISSUE TITLE
[Image Optimizer] Error received from reSmush for status ID

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1697] opened 2019-04-09 17:06 UTC
@JakeBooher From this bug [here](https://github.com/Audentio/xf2addon-issues/issues/1378), I Missed notification from this post. So see the following query output.

![ScreenShot01013](https://user-images.githubusercontent.com/6899856/55820118-9fc01400-5afa-11e9-90fe-b121e44cc6b7.png)

**Comment by LukasWieditz** [comment] 2019-04-10 11:08
Duplicate of #1378

**Closed by LukasWieditz** 2019-04-10 11:08 UTC
Labels: duplicate
