### ISSUE TITLE
[QA Forums] ErrorException: Fatal Error: Access level to ThemeHouse\QAForums\XF\FindNew\Thread::applyFilters() must be public

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1611] opened 2019-03-23 10:09 UTC
````
ErrorException: Fatal Error: Access level to ThemeHouse\QAForums\XF\FindNew\Thread::applyFilters() must be public (as in class ThemeHouse\Topics\XF\FindNew\Thread) src/addons/ThemeHouse/QAForums/XF/FindNew/Thread.php:0 

Generated by: Unknown account Mar 23, 2019 at 3:54 PM 

Stack trace

#0 [internal function]: XF::handleFatalError()
#1 {main}

Request state

array(4) {
  ["url"] => string(22) "/whats-new/posts/1391/"
  ["referrer"] => bool(false)
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}
````

**Comment by Nirjonadda** [comment] 2019-03-23 15:05
@jonw316 Look like the `/whats-new/posts/` page completely blank. Please let me know how to fixing without disabling QA Forums or Topics add-on?

**Comment by jonw316** [comment] 2019-03-23 15:07
Duplicate of #1544.
This will be fixed in the next release of Topics.

**Closed by jonw316** 2019-03-23 15:07 UTC

**Comment by Nirjonadda** [comment] 2019-03-23 15:55
Any ETA for this release? Our live site having this issue.
