### ISSUE TITLE
[TH] Donate - issue with Stripe's apple pay support

### ISSUE THREAD

**Issue by JakeBooher** [Audentio/xf2addon-issues#504] opened 2018-06-10 15:12 UTC
https://xenforo.com/community/threads/th-donate-paid.145264/page-8#post-1259510

**Comment by LukasWieditz** [comment] 2018-08-30 14:35
Cannot replicate this, seems to work fine for me.

**Comment by LukasWieditz** [comment] 2018-10-19 13:43
Closing this for now, as we're unable to reproduce it. As he described it as "not showing up", he might simply have not selected it in the backend as available payment provider.

**Closed by LukasWieditz** 2018-10-19 13:43 UTC
Labels: Bug, Cant Replicate
