### ISSUE TITLE
Post comments page navigation getting calculated incorrectly.

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2addon-issues#1546] opened 2019-02-27 21:51 UTC
Still showing the pagination item for pages that no longer exist. When clicking on a pagination item that does not actually contain messages, it simply routes to the last applicable page. The issue I believe is simply that the pagination component doesn't know how many pages it should display.

**Comment by LukasWieditz** [comment] 2019-03-04 10:21
Duplicate of #1424

**Closed by LukasWieditz** 2019-03-04 10:21 UTC
Labels: bug
