### ISSUE TITLE
UIX 2.1.0.2 (io) - Template Errors Template public:_widget_thuix_userNavWidget

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2addon-issues#1479] opened 2019-02-08 19:16 UTC
ErrorException: Template error: Template public:_widget_thuix_userNavWidget is unknown src/XF/Template/Templater.php:611
Generated by: nik Feb 8, 2019 at 7:11 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/nginx/dom...', 611, Array)
#1 src/XF/Template/Templater.php(611): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(562): XF\Template\Templater->getTemplateData('public', '_widget_thuix_u...')
#3 src/XF/Template/Templater.php(1293): XF\Template\Templater->getTemplateCode('public', '_widget_thuix_u...')
#4 src/XF/Widget/Html.php(16): XF\Template\Templater->renderTemplate('_widget_thuix_u...', Array)
#5 internal_data/code_cache/widgets/_13_thuix_footer_userNavWidget.php(5): XF\Widget\Html->render()
#6 src/XF/Template/Templater.php(6569): XF\SubContainer\Widget->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array, Array)
#7 src/XF/SubContainer/Widget.php(168): XF\Template\Templater->renderWidgetClosure(Object(Closure), Array)
#8 src/XF/Template/Templater.php(1613): XF\SubContainer\Widget->getCompiledWidget(Array, Array)
#9 src/addons/ThemeHouse/UIX/Util/UIX.php(50): XF\Template\Templater->widgetPosition('th_footer_uix')
#10 src/addons/ThemeHouse/UIX/Listener/AppPubRenderPage.php(21): ThemeHouse\UIX\Util\UIX->getFooterWidgets(Object(ThemeHouse\UIX\XF\Template\Templater))
#11 [internal function]: ThemeHouse\UIX\Listener\AppPubRenderPage::appPubRenderPage(Object(XF\Pub\App), Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#12 src/XF/Extension.php(67): call_user_func_array(Array, Array)
#13 src/XF/App.php(2647): XF\Extension->fire('app_pub_render_...', Array, NULL)
#14 src/XF/Pub/App.php(545): XF\App->fire('app_pub_render_...', Array)
#15 src/XF/App.php(1988): XF\Pub\App->renderPageHtml('

	

...', Array, Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#16 src/XF/Mvc/Dispatcher.php(362): XF\App->renderPage('

	

...', Object(XF\Mvc\Reply\View), Object(XF\Mvc\Renderer\Html))
#17 src/XF/Mvc/Dispatcher.php(53): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'html')
#18 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#19 src/XF.php(390): XF\App->run()
#20 index.php(20): XF::runApp('XF\\Pub\\App')
#21 {main}
Request state
array(4) {
  ["url"] => string(11) "/community/"
  ["referrer"] => string(61) "https://mysite.com/community/admin.php?logs/server-errors/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(0) {
  }
}

**Comment by jonw316** [comment] 2019-02-11 12:22
Duplicate of #1478

**Closed by jonw316** 2019-02-11 12:22 UTC
Labels: duplicate
