### ISSUE TITLE
[TH] Post Comments - Hide Comment button after nesting depth limited

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2addon-issues#1073] opened 2018-10-29 10:51 UTC
Please add option Hide Comment button after nesting depth limit over.

![screenshot00630](https://user-images.githubusercontent.com/6899856/47645288-d28bd680-db70-11e8-9e0a-e8c6dce01a36.png)

**Comment by LukasWieditz** [comment] 2018-10-29 10:53
Duplicate of #1006

**Closed by LukasWieditz** 2018-10-29 10:53 UTC
